
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINNEWS BEGINRESPONSE ENDNEWS ENDRESPONSE SKIPTAG TEXT\n    document : news_content\n    \n    news_content :  BEGINNEWS content ENDNEWS\n                | BEGINRESPONSE content ENDRESPONSE\n    \n    content : SKIPTAG content content\n            | TEXT content\n            |\n    '
    
_lr_action_items = {'BEGINNEWS':([0,],[3,]),'BEGINRESPONSE':([0,],[4,]),'$end':([1,2,9,12,],[0,-1,-2,-3,]),'SKIPTAG':([3,4,6,7,10,11,13,],[6,6,6,6,6,-5,-4,]),'TEXT':([3,4,6,7,10,11,13,],[7,7,7,7,7,-5,-4,]),'ENDNEWS':([3,5,6,7,10,11,13,],[-6,9,-6,-6,-6,-5,-4,]),'ENDRESPONSE':([4,6,7,8,10,11,13,],[-6,-6,-6,12,-6,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'news_content':([0,],[2,]),'content':([3,4,6,7,10,],[5,8,10,11,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> news_content','document',1,'p_document','Query2.py',10),
  ('news_content -> BEGINNEWS content ENDNEWS','news_content',3,'p_news_content','Query2.py',15),
  ('news_content -> BEGINRESPONSE content ENDRESPONSE','news_content',3,'p_news_content','Query2.py',16),
  ('content -> SKIPTAG content content','content',3,'p_content','Query2.py',21),
  ('content -> TEXT content','content',2,'p_content','Query2.py',22),
  ('content -> <empty>','content',0,'p_content','Query2.py',23),
]
