
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEBODY CLOSEDATA CLOSEHEAD CLOSEHEADER CLOSEHREF CLOSENOBR CLOSEROW CLOSETABLE CONTENT ENDSKIPS OPENBODY OPENBR OPENDATA OPENHEAD OPENHEADER OPENHREF OPENNOBR OPENROW OPENTABLE\n    start : OPENTABLE handleheader handlebody CLOSETABLE\n    \n     handleheader : OPENHEAD OPENROW handleheaderdata CLOSEROW CLOSEHEAD\n     \n     handleheaderdata : OPENHEADER content CLOSEHEADER handleheaderdata\n                      | empty\n     \n     handlebody : OPENBODY handlerow CLOSEBODY\n     \n     handlerow : OPENROW handledata endskip CLOSEROW handlerow\n               | empty\n     \n     handledata : OPENDATA content CLOSEDATA handledata\n                | OPENDATA OPENHREF content CLOSEHREF CLOSEDATA handledata\n                | OPENDATA OPENNOBR content CLOSENOBR CLOSEDATA handledata\n                | empty\n     \n     endskip : ENDSKIPS handledata endskip\n             | empty\n     \n    content : CONTENT content\n            | CONTENT OPENBR content\n            | CONTENT OPENBR OPENNOBR content CLOSENOBR content\n            | empty\n    \n    empty :\n    '
    
_lr_action_items = {'OPENTABLE':([0,],[2,]),'$end':([1,8,],[0,-1,]),'OPENHEAD':([2,],[4,]),'OPENBODY':([3,29,],[6,-2,]),'OPENROW':([4,6,33,],[7,10,10,]),'CLOSETABLE':([5,15,],[8,-5,]),'CLOSEBODY':([6,9,11,33,41,],[-18,15,-7,-18,-6,]),'OPENHEADER':([7,30,],[13,13,]),'CLOSEROW':([7,10,12,14,16,18,23,24,25,30,34,35,38,42,43,47,48,50,51,],[-18,-18,19,-4,-18,-11,33,-18,-13,-18,-18,-18,-3,-12,-8,-18,-18,-9,-10,]),'OPENDATA':([10,24,35,47,48,],[17,17,17,17,17,]),'ENDSKIPS':([10,16,18,24,34,35,43,47,48,50,51,],[-18,24,-11,-18,24,-18,-8,-18,-18,-9,-10,]),'CONTENT':([13,17,21,27,28,32,40,49,],[21,21,21,21,21,21,21,21,]),'CLOSEHEADER':([13,20,21,22,31,32,39,49,52,],[-18,30,-18,-17,-14,-18,-15,-18,-16,]),'OPENHREF':([17,],[27,]),'OPENNOBR':([17,32,],[28,40,]),'CLOSEDATA':([17,21,22,26,31,32,39,44,45,49,52,],[-18,-18,-17,35,-14,-18,-15,47,48,-18,-16,]),'CLOSEHEAD':([19,],[29,]),'OPENBR':([21,],[32,]),'CLOSEHREF':([21,22,27,31,32,36,39,49,52,],[-18,-17,-18,-14,-18,44,-15,-18,-16,]),'CLOSENOBR':([21,22,28,31,32,37,39,40,46,49,52,],[-18,-17,-18,-14,-18,45,-15,-18,49,-18,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'handleheader':([2,],[3,]),'handlebody':([3,],[5,]),'handlerow':([6,33,],[9,41,]),'empty':([6,7,10,13,16,17,21,24,27,28,30,32,33,34,35,40,47,48,49,],[11,14,18,22,25,22,22,18,22,22,14,22,11,25,18,22,18,18,22,]),'handleheaderdata':([7,30,],[12,38,]),'handledata':([10,24,35,47,48,],[16,34,43,50,51,]),'content':([13,17,21,27,28,32,40,49,],[20,26,31,36,37,39,46,52,]),'endskip':([16,34,],[23,42,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> OPENTABLE handleheader handlebody CLOSETABLE','start',4,'p_start','Query1.py',106),
  ('handleheader -> OPENHEAD OPENROW handleheaderdata CLOSEROW CLOSEHEAD','handleheader',5,'p_handleheader','Query1.py',112),
  ('handleheaderdata -> OPENHEADER content CLOSEHEADER handleheaderdata','handleheaderdata',4,'p_handleheaderdata','Query1.py',118),
  ('handleheaderdata -> empty','handleheaderdata',1,'p_handleheaderdata','Query1.py',119),
  ('handlebody -> OPENBODY handlerow CLOSEBODY','handlebody',3,'p_handlebody','Query1.py',125),
  ('handlerow -> OPENROW handledata endskip CLOSEROW handlerow','handlerow',5,'p_handlerow','Query1.py',131),
  ('handlerow -> empty','handlerow',1,'p_handlerow','Query1.py',132),
  ('handledata -> OPENDATA content CLOSEDATA handledata','handledata',4,'p_handledata','Query1.py',138),
  ('handledata -> OPENDATA OPENHREF content CLOSEHREF CLOSEDATA handledata','handledata',6,'p_handledata','Query1.py',139),
  ('handledata -> OPENDATA OPENNOBR content CLOSENOBR CLOSEDATA handledata','handledata',6,'p_handledata','Query1.py',140),
  ('handledata -> empty','handledata',1,'p_handledata','Query1.py',141),
  ('endskip -> ENDSKIPS handledata endskip','endskip',3,'p_endskip','Query1.py',150),
  ('endskip -> empty','endskip',1,'p_endskip','Query1.py',151),
  ('content -> CONTENT content','content',2,'p_content','Query1.py',157),
  ('content -> CONTENT OPENBR content','content',3,'p_content','Query1.py',158),
  ('content -> CONTENT OPENBR OPENNOBR content CLOSENOBR content','content',6,'p_content','Query1.py',159),
  ('content -> empty','content',1,'p_content','Query1.py',160),
  ('empty -> <empty>','empty',0,'p_empty','Query1.py',167),
]
